/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VertragBestaetigenRouteImport } from './routes/vertrag-bestaetigen'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestPasswortZuruecksetzenRouteImport } from './routes/_guest/passwort-zuruecksetzen'
import { Route as GuestPasswortVergessenRouteImport } from './routes/_guest/passwort-vergessen'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthPasswortSetzenRouteImport } from './routes/_auth/passwort-setzen'
import { Route as AuthInternRouteImport } from './routes/_auth/intern'
import { Route as AuthEmailVerifizierenRouteImport } from './routes/_auth/email-verifizieren'
import { Route as AuthInternIndexRouteImport } from './routes/_auth/intern.index'
import { Route as GuestAccountEinrichtenRouteImport } from './routes/_guest/account.einrichten'
import { Route as AuthKundeCustomerIdRouteImport } from './routes/_auth/kunde.$customerId'
import { Route as AuthKundeCustomerIdIndexRouteImport } from './routes/_auth/kunde.$customerId.index'
import { Route as AuthKundeCustomerIdProfilRouteImport } from './routes/_auth/kunde.$customerId.profil'
import { Route as AuthKundeCustomerIdPostfachRouteImport } from './routes/_auth/kunde.$customerId.postfach'
import { Route as AuthKundeCustomerIdKontaktRouteImport } from './routes/_auth/kunde.$customerId.kontakt'
import { Route as AuthKundeCustomerIdVertragContractIdRouteImport } from './routes/_auth/kunde.$customerId.vertrag.$contractId'
import { Route as AuthKundeCustomerIdVertragContractIdIndexRouteImport } from './routes/_auth/kunde.$customerId.vertrag.$contractId.index'
import { Route as AuthKundeCustomerIdVertragContractIdAendernFormTypeRouteImport } from './routes/_auth/kunde.$customerId.vertrag.$contractId.aendern.$formType'

const VertragBestaetigenRoute = VertragBestaetigenRouteImport.update({
  id: '/vertrag-bestaetigen',
  path: '/vertrag-bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestPasswortZuruecksetzenRoute =
  GuestPasswortZuruecksetzenRouteImport.update({
    id: '/passwort-zuruecksetzen',
    path: '/passwort-zuruecksetzen',
    getParentRoute: () => GuestRoute,
  } as any)
const GuestPasswortVergessenRoute = GuestPasswortVergessenRouteImport.update({
  id: '/passwort-vergessen',
  path: '/passwort-vergessen',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthPasswortSetzenRoute = AuthPasswortSetzenRouteImport.update({
  id: '/passwort-setzen',
  path: '/passwort-setzen',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInternRoute = AuthInternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerifizierenRoute = AuthEmailVerifizierenRouteImport.update({
  id: '/email-verifizieren',
  path: '/email-verifizieren',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInternIndexRoute = AuthInternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInternRoute,
} as any)
const GuestAccountEinrichtenRoute = GuestAccountEinrichtenRouteImport.update({
  id: '/account/einrichten',
  path: '/account/einrichten',
  getParentRoute: () => GuestRoute,
} as any)
const AuthKundeCustomerIdRoute = AuthKundeCustomerIdRouteImport.update({
  id: '/kunde/$customerId',
  path: '/kunde/$customerId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKundeCustomerIdIndexRoute =
  AuthKundeCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthKundeCustomerIdRoute,
  } as any)
const AuthKundeCustomerIdProfilRoute =
  AuthKundeCustomerIdProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthKundeCustomerIdRoute,
  } as any)
const AuthKundeCustomerIdPostfachRoute =
  AuthKundeCustomerIdPostfachRouteImport.update({
    id: '/postfach',
    path: '/postfach',
    getParentRoute: () => AuthKundeCustomerIdRoute,
  } as any)
const AuthKundeCustomerIdKontaktRoute =
  AuthKundeCustomerIdKontaktRouteImport.update({
    id: '/kontakt',
    path: '/kontakt',
    getParentRoute: () => AuthKundeCustomerIdRoute,
  } as any)
const AuthKundeCustomerIdVertragContractIdRoute =
  AuthKundeCustomerIdVertragContractIdRouteImport.update({
    id: '/vertrag/$contractId',
    path: '/vertrag/$contractId',
    getParentRoute: () => AuthKundeCustomerIdRoute,
  } as any)
const AuthKundeCustomerIdVertragContractIdIndexRoute =
  AuthKundeCustomerIdVertragContractIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthKundeCustomerIdVertragContractIdRoute,
  } as any)
const AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute =
  AuthKundeCustomerIdVertragContractIdAendernFormTypeRouteImport.update({
    id: '/aendern/$formType',
    path: '/aendern/$formType',
    getParentRoute: () => AuthKundeCustomerIdVertragContractIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vertrag-bestaetigen': typeof VertragBestaetigenRoute
  '/email-verifizieren': typeof AuthEmailVerifizierenRoute
  '/intern': typeof AuthInternRouteWithChildren
  '/passwort-setzen': typeof AuthPasswortSetzenRoute
  '/login': typeof GuestLoginRoute
  '/passwort-vergessen': typeof GuestPasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof GuestPasswortZuruecksetzenRoute
  '/kunde/$customerId': typeof AuthKundeCustomerIdRouteWithChildren
  '/account/einrichten': typeof GuestAccountEinrichtenRoute
  '/intern/': typeof AuthInternIndexRoute
  '/kunde/$customerId/kontakt': typeof AuthKundeCustomerIdKontaktRoute
  '/kunde/$customerId/postfach': typeof AuthKundeCustomerIdPostfachRoute
  '/kunde/$customerId/profil': typeof AuthKundeCustomerIdProfilRoute
  '/kunde/$customerId/': typeof AuthKundeCustomerIdIndexRoute
  '/kunde/$customerId/vertrag/$contractId': typeof AuthKundeCustomerIdVertragContractIdRouteWithChildren
  '/kunde/$customerId/vertrag/$contractId/': typeof AuthKundeCustomerIdVertragContractIdIndexRoute
  '/kunde/$customerId/vertrag/$contractId/aendern/$formType': typeof AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vertrag-bestaetigen': typeof VertragBestaetigenRoute
  '/email-verifizieren': typeof AuthEmailVerifizierenRoute
  '/passwort-setzen': typeof AuthPasswortSetzenRoute
  '/login': typeof GuestLoginRoute
  '/passwort-vergessen': typeof GuestPasswortVergessenRoute
  '/passwort-zuruecksetzen': typeof GuestPasswortZuruecksetzenRoute
  '/account/einrichten': typeof GuestAccountEinrichtenRoute
  '/intern': typeof AuthInternIndexRoute
  '/kunde/$customerId/kontakt': typeof AuthKundeCustomerIdKontaktRoute
  '/kunde/$customerId/postfach': typeof AuthKundeCustomerIdPostfachRoute
  '/kunde/$customerId/profil': typeof AuthKundeCustomerIdProfilRoute
  '/kunde/$customerId': typeof AuthKundeCustomerIdIndexRoute
  '/kunde/$customerId/vertrag/$contractId': typeof AuthKundeCustomerIdVertragContractIdIndexRoute
  '/kunde/$customerId/vertrag/$contractId/aendern/$formType': typeof AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/vertrag-bestaetigen': typeof VertragBestaetigenRoute
  '/_auth/email-verifizieren': typeof AuthEmailVerifizierenRoute
  '/_auth/intern': typeof AuthInternRouteWithChildren
  '/_auth/passwort-setzen': typeof AuthPasswortSetzenRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/passwort-vergessen': typeof GuestPasswortVergessenRoute
  '/_guest/passwort-zuruecksetzen': typeof GuestPasswortZuruecksetzenRoute
  '/_auth/kunde/$customerId': typeof AuthKundeCustomerIdRouteWithChildren
  '/_guest/account/einrichten': typeof GuestAccountEinrichtenRoute
  '/_auth/intern/': typeof AuthInternIndexRoute
  '/_auth/kunde/$customerId/kontakt': typeof AuthKundeCustomerIdKontaktRoute
  '/_auth/kunde/$customerId/postfach': typeof AuthKundeCustomerIdPostfachRoute
  '/_auth/kunde/$customerId/profil': typeof AuthKundeCustomerIdProfilRoute
  '/_auth/kunde/$customerId/': typeof AuthKundeCustomerIdIndexRoute
  '/_auth/kunde/$customerId/vertrag/$contractId': typeof AuthKundeCustomerIdVertragContractIdRouteWithChildren
  '/_auth/kunde/$customerId/vertrag/$contractId/': typeof AuthKundeCustomerIdVertragContractIdIndexRoute
  '/_auth/kunde/$customerId/vertrag/$contractId/aendern/$formType': typeof AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vertrag-bestaetigen'
    | '/email-verifizieren'
    | '/intern'
    | '/passwort-setzen'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/kunde/$customerId'
    | '/account/einrichten'
    | '/intern/'
    | '/kunde/$customerId/kontakt'
    | '/kunde/$customerId/postfach'
    | '/kunde/$customerId/profil'
    | '/kunde/$customerId/'
    | '/kunde/$customerId/vertrag/$contractId'
    | '/kunde/$customerId/vertrag/$contractId/'
    | '/kunde/$customerId/vertrag/$contractId/aendern/$formType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vertrag-bestaetigen'
    | '/email-verifizieren'
    | '/passwort-setzen'
    | '/login'
    | '/passwort-vergessen'
    | '/passwort-zuruecksetzen'
    | '/account/einrichten'
    | '/intern'
    | '/kunde/$customerId/kontakt'
    | '/kunde/$customerId/postfach'
    | '/kunde/$customerId/profil'
    | '/kunde/$customerId'
    | '/kunde/$customerId/vertrag/$contractId'
    | '/kunde/$customerId/vertrag/$contractId/aendern/$formType'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/vertrag-bestaetigen'
    | '/_auth/email-verifizieren'
    | '/_auth/intern'
    | '/_auth/passwort-setzen'
    | '/_guest/login'
    | '/_guest/passwort-vergessen'
    | '/_guest/passwort-zuruecksetzen'
    | '/_auth/kunde/$customerId'
    | '/_guest/account/einrichten'
    | '/_auth/intern/'
    | '/_auth/kunde/$customerId/kontakt'
    | '/_auth/kunde/$customerId/postfach'
    | '/_auth/kunde/$customerId/profil'
    | '/_auth/kunde/$customerId/'
    | '/_auth/kunde/$customerId/vertrag/$contractId'
    | '/_auth/kunde/$customerId/vertrag/$contractId/'
    | '/_auth/kunde/$customerId/vertrag/$contractId/aendern/$formType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  VertragBestaetigenRoute: typeof VertragBestaetigenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vertrag-bestaetigen': {
      id: '/vertrag-bestaetigen'
      path: '/vertrag-bestaetigen'
      fullPath: '/vertrag-bestaetigen'
      preLoaderRoute: typeof VertragBestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/passwort-zuruecksetzen': {
      id: '/_guest/passwort-zuruecksetzen'
      path: '/passwort-zuruecksetzen'
      fullPath: '/passwort-zuruecksetzen'
      preLoaderRoute: typeof GuestPasswortZuruecksetzenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/passwort-vergessen': {
      id: '/_guest/passwort-vergessen'
      path: '/passwort-vergessen'
      fullPath: '/passwort-vergessen'
      preLoaderRoute: typeof GuestPasswortVergessenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/passwort-setzen': {
      id: '/_auth/passwort-setzen'
      path: '/passwort-setzen'
      fullPath: '/passwort-setzen'
      preLoaderRoute: typeof AuthPasswortSetzenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/intern': {
      id: '/_auth/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof AuthInternRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/email-verifizieren': {
      id: '/_auth/email-verifizieren'
      path: '/email-verifizieren'
      fullPath: '/email-verifizieren'
      preLoaderRoute: typeof AuthEmailVerifizierenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/intern/': {
      id: '/_auth/intern/'
      path: '/'
      fullPath: '/intern/'
      preLoaderRoute: typeof AuthInternIndexRouteImport
      parentRoute: typeof AuthInternRoute
    }
    '/_guest/account/einrichten': {
      id: '/_guest/account/einrichten'
      path: '/account/einrichten'
      fullPath: '/account/einrichten'
      preLoaderRoute: typeof GuestAccountEinrichtenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/kunde/$customerId': {
      id: '/_auth/kunde/$customerId'
      path: '/kunde/$customerId'
      fullPath: '/kunde/$customerId'
      preLoaderRoute: typeof AuthKundeCustomerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kunde/$customerId/': {
      id: '/_auth/kunde/$customerId/'
      path: '/'
      fullPath: '/kunde/$customerId/'
      preLoaderRoute: typeof AuthKundeCustomerIdIndexRouteImport
      parentRoute: typeof AuthKundeCustomerIdRoute
    }
    '/_auth/kunde/$customerId/profil': {
      id: '/_auth/kunde/$customerId/profil'
      path: '/profil'
      fullPath: '/kunde/$customerId/profil'
      preLoaderRoute: typeof AuthKundeCustomerIdProfilRouteImport
      parentRoute: typeof AuthKundeCustomerIdRoute
    }
    '/_auth/kunde/$customerId/postfach': {
      id: '/_auth/kunde/$customerId/postfach'
      path: '/postfach'
      fullPath: '/kunde/$customerId/postfach'
      preLoaderRoute: typeof AuthKundeCustomerIdPostfachRouteImport
      parentRoute: typeof AuthKundeCustomerIdRoute
    }
    '/_auth/kunde/$customerId/kontakt': {
      id: '/_auth/kunde/$customerId/kontakt'
      path: '/kontakt'
      fullPath: '/kunde/$customerId/kontakt'
      preLoaderRoute: typeof AuthKundeCustomerIdKontaktRouteImport
      parentRoute: typeof AuthKundeCustomerIdRoute
    }
    '/_auth/kunde/$customerId/vertrag/$contractId': {
      id: '/_auth/kunde/$customerId/vertrag/$contractId'
      path: '/vertrag/$contractId'
      fullPath: '/kunde/$customerId/vertrag/$contractId'
      preLoaderRoute: typeof AuthKundeCustomerIdVertragContractIdRouteImport
      parentRoute: typeof AuthKundeCustomerIdRoute
    }
    '/_auth/kunde/$customerId/vertrag/$contractId/': {
      id: '/_auth/kunde/$customerId/vertrag/$contractId/'
      path: '/'
      fullPath: '/kunde/$customerId/vertrag/$contractId/'
      preLoaderRoute: typeof AuthKundeCustomerIdVertragContractIdIndexRouteImport
      parentRoute: typeof AuthKundeCustomerIdVertragContractIdRoute
    }
    '/_auth/kunde/$customerId/vertrag/$contractId/aendern/$formType': {
      id: '/_auth/kunde/$customerId/vertrag/$contractId/aendern/$formType'
      path: '/aendern/$formType'
      fullPath: '/kunde/$customerId/vertrag/$contractId/aendern/$formType'
      preLoaderRoute: typeof AuthKundeCustomerIdVertragContractIdAendernFormTypeRouteImport
      parentRoute: typeof AuthKundeCustomerIdVertragContractIdRoute
    }
  }
}

interface AuthInternRouteChildren {
  AuthInternIndexRoute: typeof AuthInternIndexRoute
}

const AuthInternRouteChildren: AuthInternRouteChildren = {
  AuthInternIndexRoute: AuthInternIndexRoute,
}

const AuthInternRouteWithChildren = AuthInternRoute._addFileChildren(
  AuthInternRouteChildren,
)

interface AuthKundeCustomerIdVertragContractIdRouteChildren {
  AuthKundeCustomerIdVertragContractIdIndexRoute: typeof AuthKundeCustomerIdVertragContractIdIndexRoute
  AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute: typeof AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute
}

const AuthKundeCustomerIdVertragContractIdRouteChildren: AuthKundeCustomerIdVertragContractIdRouteChildren =
  {
    AuthKundeCustomerIdVertragContractIdIndexRoute:
      AuthKundeCustomerIdVertragContractIdIndexRoute,
    AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute:
      AuthKundeCustomerIdVertragContractIdAendernFormTypeRoute,
  }

const AuthKundeCustomerIdVertragContractIdRouteWithChildren =
  AuthKundeCustomerIdVertragContractIdRoute._addFileChildren(
    AuthKundeCustomerIdVertragContractIdRouteChildren,
  )

interface AuthKundeCustomerIdRouteChildren {
  AuthKundeCustomerIdKontaktRoute: typeof AuthKundeCustomerIdKontaktRoute
  AuthKundeCustomerIdPostfachRoute: typeof AuthKundeCustomerIdPostfachRoute
  AuthKundeCustomerIdProfilRoute: typeof AuthKundeCustomerIdProfilRoute
  AuthKundeCustomerIdIndexRoute: typeof AuthKundeCustomerIdIndexRoute
  AuthKundeCustomerIdVertragContractIdRoute: typeof AuthKundeCustomerIdVertragContractIdRouteWithChildren
}

const AuthKundeCustomerIdRouteChildren: AuthKundeCustomerIdRouteChildren = {
  AuthKundeCustomerIdKontaktRoute: AuthKundeCustomerIdKontaktRoute,
  AuthKundeCustomerIdPostfachRoute: AuthKundeCustomerIdPostfachRoute,
  AuthKundeCustomerIdProfilRoute: AuthKundeCustomerIdProfilRoute,
  AuthKundeCustomerIdIndexRoute: AuthKundeCustomerIdIndexRoute,
  AuthKundeCustomerIdVertragContractIdRoute:
    AuthKundeCustomerIdVertragContractIdRouteWithChildren,
}

const AuthKundeCustomerIdRouteWithChildren =
  AuthKundeCustomerIdRoute._addFileChildren(AuthKundeCustomerIdRouteChildren)

interface AuthRouteChildren {
  AuthEmailVerifizierenRoute: typeof AuthEmailVerifizierenRoute
  AuthInternRoute: typeof AuthInternRouteWithChildren
  AuthPasswortSetzenRoute: typeof AuthPasswortSetzenRoute
  AuthKundeCustomerIdRoute: typeof AuthKundeCustomerIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailVerifizierenRoute: AuthEmailVerifizierenRoute,
  AuthInternRoute: AuthInternRouteWithChildren,
  AuthPasswortSetzenRoute: AuthPasswortSetzenRoute,
  AuthKundeCustomerIdRoute: AuthKundeCustomerIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPasswortVergessenRoute: typeof GuestPasswortVergessenRoute
  GuestPasswortZuruecksetzenRoute: typeof GuestPasswortZuruecksetzenRoute
  GuestAccountEinrichtenRoute: typeof GuestAccountEinrichtenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestPasswortVergessenRoute: GuestPasswortVergessenRoute,
  GuestPasswortZuruecksetzenRoute: GuestPasswortZuruecksetzenRoute,
  GuestAccountEinrichtenRoute: GuestAccountEinrichtenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  VertragBestaetigenRoute: VertragBestaetigenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
